create table orders (
    id            uuid primary key,
    reference     varchar(32)  not null unique,
    description   varchar(255) not null,
    amount        bigint       not null check (amount > 0),
    customer_name varchar(100) not null,
    status        varchar(20)  not null,
    created_at    timestamp with time zone not null,
    expires_at    timestamp with time zone not null,
    paid_at       timestamp with time zone,
    version       bigint       not null
);

create table payment_attempts (
    id                uuid primary key,
    order_id          uuid         not null references orders (id),
    provider          varchar(20)  not null,
    channel           varchar(20)  not null,
    provider_ref      varchar(100),
    status            varchar(20)  not null,
    instruction_type  varchar(30),
    instruction_value varchar(2048),
    expires_at        timestamp with time zone not null,
    created_at        timestamp with time zone not null,
    updated_at        timestamp with time zone not null,
    version           bigint       not null,
    constraint uq_payment_provider_ref unique (provider, provider_ref)
);

-- Latest payment of an order (status polling) and the expiry job's scan.
create index idx_payment_attempts_order on payment_attempts (order_id, created_at);
create index idx_payment_attempts_pending on payment_attempts (status, expires_at);

create table webhook_events (
    id          bigint generated by default as identity primary key,
    provider    varchar(20)  not null,
    event_key   varchar(200) not null,
    received_at timestamp with time zone not null,
    constraint uq_webhook_event unique (provider, event_key)
);
