create table products (
    id          varchar(40)  primary key,
    name        varchar(120) not null,
    description varchar(500) not null,
    category    varchar(40)  not null,
    icon        varchar(60)  not null,
    price       bigint       not null check (price > 0),
    active      boolean      not null,
    sort_order  int          not null
);

create table order_items (
    id           bigint generated by default as identity primary key,
    order_id     uuid         not null references orders (id),
    product_id   varchar(40)  not null references products (id),
    -- Name and price are copied so later catalogue edits never change a placed order.
    product_name varchar(120) not null,
    unit_price   bigint       not null,
    quantity     int          not null check (quantity between 1 and 10)
);

create index idx_order_items_order on order_items (order_id);

alter table orders add column customer_email varchar(254);
create index idx_orders_created on orders (created_at);

alter table webhook_events add column attempt_id uuid references payment_attempts (id);
alter table webhook_events add column confirmed_status varchar(20);
alter table webhook_events add column outcome varchar(20);

insert into products (id, name, description, category, icon, price, active, sort_order) values
('course-k8s', 'Kubernetes for Developers', 'Video course: deploy, scale, and monitor your apps on Kubernetes, from Dockerfile to autoscaling.', 'Course', 'i-lucide-ship-wheel', 249000, true, 1),
('course-nuxt', 'Nuxt 4 Fundamentals', 'Video course: build a fast, SEO-friendly web app with Nuxt 4, Nuxt UI, and server routes.', 'Course', 'i-lucide-graduation-cap', 199000, true, 2),
('ebook-api', 'Clean API Design', 'E-book: REST API patterns for pagination, errors, idempotency, and webhooks, with examples.', 'E-book', 'i-lucide-book-open', 79000, true, 3),
('template-dashboard', 'Admin Dashboard Template', 'Nuxt UI admin template with auth, tables, charts, and dark mode. Lifetime updates.', 'Template', 'i-lucide-layout-dashboard', 149000, true, 4),
('membership-pro', 'Pro Membership, 1 Month', 'Access to every course and template, plus the monthly live Q&A.', 'Membership', 'i-lucide-crown', 99000, true, 5),
('review-1h', '1-Hour Code Review', 'A recorded review of your repository with a written list of fixes, ordered by impact.', 'Service', 'i-lucide-messages-square', 350000, true, 6);
